# Generated by Django 5.0.1 on 2024-01-16 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("juice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="juice",
            name="slug",
            field=models.SlugField(
                default=datetime.datetime(
                    2024, 1, 16, 14, 2, 17, 582504, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
